package kasir.ui;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANDIKA
 */
public final class Form_Data_Barang extends javax.swing.JFrame {
     private final DefaultTableModel model;
     koneksi koneksi = new koneksi();
     
     
     
     private void autonumber(){
        try{
            Connection c = koneksi.getConnection();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tb_databarang ORDER BY Kode_Barang DESC";
            ResultSet r = s.executeQuery(sql);
            if (r.next()){
                String Kode_Barang = r.getString("Kode_Barang").substring(2);
                String BR = "" + (Integer.parseInt(Kode_Barang) + 1);
                String Nol = "";
                
                if(BR.length()==1){
                    Nol = "00";
                }else if(BR.length()==2){
                    Nol = "0";
                }else if(BR.length()==3){
                    Nol = "";
                }
                
                KodeBarang_TEXT.setText("BR" + Nol + BR);
                
            }else{
                KodeBarang_TEXT.setText("BR001");
            }
            r.close();
            s.close();
        }catch(Exception e){
            System.out.println( e);
        }
    }
     public void clear(){
        NamaBarang_TEXT.setText("");
        HargaJual_TEXT.setText("");
    }
     public void loadData(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try{
            Connection c = koneksi.getConnection();
            try (Statement s = c.createStatement()) {
                String sql = "SELECT * FROM tb_databarang";
                try (ResultSet r = s.executeQuery(sql)) {
                    while(r.next()){
                        Object[] o = new Object[6];
                        o [0] = r.getString("Kode_Barang");
                        o [1] = r.getString("Nama_Barang");
                        o [2] = r.getString("Satuan");
                        o [3] = r.getString("Stok_Barang");
                        o [4] = r.getString("Harga_Pokok");
                        o [5] = r.getString("Harga_Jual");
                        
                        model.addRow(o);
                    }
                }
            }
        }catch(SQLException e){
            System.out.println("terjadi kesalahan");
        }
    }
     public Form_Data_Barang() {
        initComponents();
        setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
        
        KodeBarang_TEXT.setEnabled(false);
        
        model = new DefaultTableModel();
        
        jTable1.setModel(model);
        
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Satuan");
        model.addColumn("Stok Barang");
        model.addColumn("Harga Pokok");
        model.addColumn("Harga Jual");
        
        loadData();
        autonumber();
    }
     public void FilterHuruf(KeyEvent a){
       if(Character.isDigit(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "masukan huruf saja!", "peringatan", JOptionPane.WARNING_MESSAGE);
       }
   }
    public void FilterAngka(KeyEvent a){
       if(Character.isAlphabetic(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "masukan angka saja!", "peringatan", JOptionPane.WARNING_MESSAGE);
       }
   }


    /**
     * Creates new form Form_Data_Barang
     */

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        KodeBarang = new javax.swing.JLabel();
        NamaBarang = new javax.swing.JLabel();
        Satuan = new javax.swing.JLabel();
        HargaPokok = new javax.swing.JLabel();
        StokBarang = new javax.swing.JLabel();
        HargaJual = new javax.swing.JLabel();
        KodeBarang_TEXT = new javax.swing.JTextField();
        NamaBarang_TEXT = new javax.swing.JTextField();
        Satuan_TEXT = new javax.swing.JTextField();
        HargaPokok_TEXT = new javax.swing.JTextField();
        StokBarang_TEXT = new javax.swing.JTextField();
        HargaJual_TEXT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btn_Ubah = new javax.swing.JButton();
        btn_Hapus = new javax.swing.JButton();
        btn_Batal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Data Barang");

        KodeBarang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        KodeBarang.setText("Kode Barang");

        NamaBarang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NamaBarang.setText("Nama Barang");

        Satuan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Satuan.setText("Satuan");

        HargaPokok.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HargaPokok.setText("Harga Pokok");

        StokBarang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        StokBarang.setText("Stok Barang");

        HargaJual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HargaJual.setText("Harga Jual");

        KodeBarang_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeBarang_TEXTActionPerformed(evt);
            }
        });

        NamaBarang_TEXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NamaBarang_TEXTKeyTyped(evt);
            }
        });

        Satuan_TEXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Satuan_TEXTKeyTyped(evt);
            }
        });

        HargaPokok_TEXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HargaPokok_TEXTKeyTyped(evt);
            }
        });

        StokBarang_TEXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StokBarang_TEXTKeyTyped(evt);
            }
        });

        HargaJual_TEXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HargaJual_TEXTKeyTyped(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Satuan", "Stok Barang", "Harga Pokok", "Harga Jual"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jTable1.setEditingColumn(6);
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btn_Ubah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Ubah.setText("UBAH");
        btn_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UbahActionPerformed(evt);
            }
        });

        btn_Hapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Hapus.setText("HAPUS");
        btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusActionPerformed(evt);
            }
        });

        btn_Batal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Batal.setText("BATAL");
        btn_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaBarang)
                            .addComponent(Satuan))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NamaBarang_TEXT)
                                .addContainerGap())
                            .addComponent(Satuan_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(HargaPokok)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(HargaPokok_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(HargaJual)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(HargaJual_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(StokBarang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(StokBarang_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(KodeBarang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(KodeBarang_TEXT))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Batal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Hapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Ubah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpan)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KodeBarang)
                    .addComponent(KodeBarang_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaBarang)
                    .addComponent(NamaBarang_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Satuan)
                    .addComponent(StokBarang)
                    .addComponent(Satuan_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StokBarang_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HargaPokok)
                    .addComponent(HargaJual)
                    .addComponent(HargaPokok_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HargaJual_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnSimpan)
                    .addComponent(btn_Ubah)
                    .addComponent(btn_Hapus)
                    .addComponent(btn_Batal))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // tombol kembali
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        // Tombol simpan
        String Kode_Barang = KodeBarang_TEXT.getText();
        String Nama_Barang = NamaBarang_TEXT.getText();
        String Satuan = Satuan_TEXT.getText();
        String Stok_Barang = StokBarang_TEXT.getText();
        String Harga_Pokok = HargaPokok_TEXT.getText();
        String Harga_Jual = HargaJual_TEXT.getText();
        
        try{
            Connection c = koneksi.getConnection();
            String sql = "INSERT INTO tb_databarang VALUES (?, ?, ?, ?, ?, ?)";
            try (PreparedStatement p = c.prepareStatement(sql)) {
                p.setString(1, Kode_Barang);
                p.setString(2, Nama_Barang);
                p.setString(3, Satuan);
                p.setString(4, Stok_Barang);
                p.setString(5, Harga_Pokok);
                p.setString(6, Harga_Jual);
                p.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
        }catch(SQLException e){
            System.out.println("Terjadi Kesalahan");
        }finally{
            loadData();
            autonumber();
            clear();
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btn_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UbahActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if(i == -1){
            return;
        }
        String Kode_Barang = (String)model.getValueAt(i, 0);
        String Nama_Barang = NamaBarang_TEXT.getText();
        String Satuan = Satuan_TEXT.getText();
        String Stok_Barang = StokBarang_TEXT.getText();
        String Harga_Pokok = HargaPokok_TEXT.getText();
        String Harga_Jual = HargaJual_TEXT.getText();
        
        try{
            Connection c = koneksi.getConnection();
            String sql = "UPDATE tb_databarang SET Nama_Barang = ?, Satuan = ?, Stok_Barang = ?, Harga_Pokok = ?, Harga_Jual = ? WHERE Kode_Barang = ?";
            try (PreparedStatement p = c.prepareStatement(sql)) {
                p.setString(1, Nama_Barang);
                p.setString(2, Satuan);
                p.setString(3, Stok_Barang);
                p.setString(4, Harga_Pokok);
                p.setString(5, Harga_Jual);
                
                p.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "Data Terubah");
            btnSimpan.setEnabled(true);
            clear();
        }catch(SQLException e){
            System.out.println("Update Error");
        }finally{
            loadData();
            autonumber();
        }

    }//GEN-LAST:event_btn_UbahActionPerformed

    
    private void btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusActionPerformed
        // TODO add your handling code here:
         int i = jTable1.getSelectedRow();
        if(i == -1){
            return;
        }
        
        String Kode_Barang = (String)model.getValueAt(i, 0);
        
        int question = JOptionPane.showConfirmDialog(null, "Yakin Anda Ingin Menghapus Data ?","Konfirmasi", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        
        if(question == JOptionPane.OK_OPTION){
            try{
                Connection c = koneksi.getConnection();
                String sql = "DELETE FROM tb_databarang WHERE Kode_Barang = ?";
                try (PreparedStatement p = c.prepareStatement(sql)) {
                    p.setString(1, Kode_Barang);
                    p.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Data Terhapus");
            }catch(SQLException e){
                System.out.println("Terjadi Kesalahab");
            }finally{
                loadData();
                autonumber();
                clear();
            }
        }
        if(question == JOptionPane.CANCEL_OPTION){
        }

    }//GEN-LAST:event_btn_HapusActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jTable1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorMoved

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        btnSimpan.setEnabled(false);
        btn_Ubah.setEnabled(true);
        btn_Hapus.setEnabled(true);
        int i = jTable1.getSelectedRow();
        if (i == -1) {
            return;
        }
        String Kode_Barang = (String) model.getValueAt(i, 0);
        KodeBarang_TEXT.setText(Kode_Barang);
        KodeBarang_TEXT.setEnabled(false);

        String Nama_Barang = (String) model.getValueAt(i, 1);
        NamaBarang_TEXT.setText(Nama_Barang);

        String Satuan = (String) model.getValueAt(i, 2);
        Satuan_TEXT.setText(Satuan);

        String Stok_Barang = (String) model.getValueAt(i, 3);
        StokBarang_TEXT.setText(Stok_Barang);

        String Harga_Pokok = (String) model.getValueAt(i, 4);
        HargaPokok_TEXT.setText(Harga_Pokok);
        
        String Harga_Jual = (String) model.getValueAt(i, 5);
        HargaJual_TEXT.setText(Harga_Jual);
    }//GEN-LAST:event_jTable1MouseClicked

    private void NamaBarang_TEXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NamaBarang_TEXTKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_NamaBarang_TEXTKeyTyped

    private void KodeBarang_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeBarang_TEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeBarang_TEXTActionPerformed

    private void Satuan_TEXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Satuan_TEXTKeyTyped
        // TODO add your handling code here:
        FilterHuruf(evt);
    }//GEN-LAST:event_Satuan_TEXTKeyTyped

    private void StokBarang_TEXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StokBarang_TEXTKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt);
    }//GEN-LAST:event_StokBarang_TEXTKeyTyped

    private void HargaPokok_TEXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HargaPokok_TEXTKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt);
    }//GEN-LAST:event_HargaPokok_TEXTKeyTyped

    private void HargaJual_TEXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HargaJual_TEXTKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt);
    }//GEN-LAST:event_HargaJual_TEXTKeyTyped

    private void btn_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BatalActionPerformed
        // TODO add your handling code here:
        clear();
        loadData();
        btnSimpan.setEnabled(true);
        autonumber();
    }//GEN-LAST:event_btn_BatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Data_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Data_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Data_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Data_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Data_Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HargaJual;
    public javax.swing.JTextField HargaJual_TEXT;
    private javax.swing.JLabel HargaPokok;
    public javax.swing.JTextField HargaPokok_TEXT;
    private javax.swing.JLabel KodeBarang;
    public javax.swing.JTextField KodeBarang_TEXT;
    private javax.swing.JLabel NamaBarang;
    public javax.swing.JTextField NamaBarang_TEXT;
    private javax.swing.JLabel Satuan;
    public javax.swing.JTextField Satuan_TEXT;
    private javax.swing.JLabel StokBarang;
    public javax.swing.JTextField StokBarang_TEXT;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btn_Batal;
    private javax.swing.JButton btn_Hapus;
    private javax.swing.JButton btn_Ubah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private Connection Connections() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}
